alias df='df -h'
alias du='du -h'
alias ll='ls -lph --color=auto --group-directories-first'
alias l='ls -1ph --color=auto --group-directories-first'
alias la='ls -Aph --color=auto --group-directories-first'
alias ls='ls -p --color=auto --group-directories-first'
alias www-browser='www-browser -o basic_color=white -o anchor_color=white' 
alias diff='colordiff'
alias free='free -m'
alias i='aptitude -y install'
alias s='aptitude -y search'
alias cp='cp --verbose'
alias v='vim -p'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='rgrep --color=auto'
