alias df='df -h'
alias du='du -h'
alias ll='ls -lph --color=auto --group-directories-first'
alias l='ls -1ph --color=auto --group-directories-first'
alias la='ls -Aph --color=auto --group-directories-first'
alias ls='ls -p --color=auto --group-directories-first'
alias www-browser='www-browser -o basic_color=white -o anchor_color=white' 
alias diff='colordiff'
alias free='free -m'
alias i='sudo aptitude -y install'
alias s='aptitude -y search'
alias update='sudo aptitude update'
alias upgrade='sudo aptitude -y upgrade'
alias cp='cp --verbose'
alias v='vim -p'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='rgrep --color=auto'
alias comprime='7z -mx=9 a'
alias desligar='sudo shutdown -h now'
alias reiniciar='sudo reboot'
alias hora='date +"%H:%M"'
alias bateria='acpi --battery --ac-adapter --details'
alias admin='sudo su'
alias cal='cal -3'
